---
- name: Install repositories
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm

#- name: Install repositories | sphagnum
#  get_url:
#    url: https://repo.sphagnum.uk/sphagnum-fc.repo
#    dest: /etc/yum.repos.d/sphagnum.repo

- name: Install repositories | workstation
  package:
    name: fedora-workstation-repositories
    state: installed

- name: Install repositories | vscode
  yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes

- name: Install repositories | Spotify
  yum_repository:
    name: spotify
    description: spotify
    baseurl: https://negativo17.org/repos/spotify/fedora-$releasever/$basearch/
    gpgkey: https://negativo17.org/repos/RPM-GPG-KEY-slaanesh
    gpgcheck: yes

- name: Install repositories | google-chrome
  dnf:
    name: google-chrome
    enablerepo: google-chrome
    state: present

- name: Install packages
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - ack
    - arandr
    - asciidoc
    - autorandr
    - blueman
    - cloc
    - code
    - composer
    - conky
    - ctags
    - curl
    - dmenu
    - dnsmasq
    - docker
    - docker-compose
    - dunst
    - evolution
    - exfalso
    - feh
    - ffmpeg
    - firefox
    - fuse-sshfs
    - gigolo
    - git
    - gitg
    - gitstats
    - google-chrome-stable
    - i3lock
    - iperf
    - ipython
    - jq
    - keychain
    - lastpass-cli
    - meld
    - mutt
    - mycli
    - neovim
    - network-manager-applet
    - nmap
    - nodejs
    - npm
    - openbox
    - pandoc
    - pass
    - pavucontrol
    - pcmanfm
    - perl-sort
    - psmisc
    - python-pip
    - python-virtualenvwrapper
    - python3-neovim
    - quodlibet
    - rpm-build
    - rpm-devel
    - rpm-sign
    - rpmdevtools
    - rpmlint
    - rubygem-asciidoctor
    - rxvt-unicode
    - sensible-utils
    - snapd
    - spectacle
    - spotify-client
    - sshuttle
    - sxhkd
    - system-config-printer
    - syncthing
    - tcpdump
    - tig
    - tint2
    - tmux
    - urlview
    - vim
    - vim-X11
    - vlc
    - volumeicon
    - w3m
    - wget
    - wireshark
    - wmctrl
    - xautolock
    - xbacklight
    - xclip
    - xdotool
    - xsel
    - xset
    - zsh
