---
- name: Install repositories
  dnf:
    name: "{{ item }}"
    state: installed
    disable_gpg_check: yes
  with_items:
    - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm

- name: Install repositories | workstation
  package:
    name: fedora-workstation-repositories
    state: installed

- name: Install repositories | docker
  shell: dnf config-manager --add-repo=https://download.docker.com/linux/fedora/docker-ce.repo
  args:
    creates:
      /etc/yum.repos.d/docker-ce.repo

- name: Install repositories | vscode
  yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes

- name: Install repositories | Spotify
  yum_repository:
    name: spotify
    description: spotify
    baseurl: https://negativo17.org/repos/spotify/fedora-$releasever/$basearch/
    gpgkey: https://negativo17.org/repos/RPM-GPG-KEY-slaanesh
    gpgcheck: yes

- name: Install repositories | google-chrome
  dnf:
    name: google-chrome
    enablerepo: google-chrome
    state: present

- name: Install packages | dnf
  package:
    name:
      - ack
      - arandr
      - autorandr
      - blueman
      - cloc
      - code
      - composer
      - conky
      - containerd.io
      - ctags
      - curl
      - dmenu
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - dunst
      - exfalso
      - feh
      - ffmpeg
      - firefox
      - fuse-sshfs
      - gigolo
      - gimp
      - git
      - git-cola
      - gitg
      - gitstats
      - google-chrome-stable
      - httpie
      - i3lock
      - iperf
      - ipython
      - jq
      - keychain
      - meld
      - mutt
      - mycli
      - neovim
      - network-manager-applet
      - nextcloud-client
      - nmap
      - nodejs
      - npm
      - openbox
      - pandoc
      - pass
      - passmenu
      - pavucontrol
      - pcmanfm
      - perl-sort
      - psmisc
      - python-pip
      - python-virtualenvwrapper
      - python3-neovim
      - quodlibet
      - remmina
      - rpm-build
      - rpm-devel
      - rpm-sign
      - rpmdevtools
      - rpmlint
      - rubygem-asciidoctor
      - rxvt-unicode
      - sensible-utils
      - snapd
      - spectacle
      - spotify-client
      - sshuttle
      - sxhkd
      - syncthing
      - system-config-printer
      - tcpdump
      - thunderbird
      - tig
      - tint2
      - tmux
      - urlview
      - vim
      - vim-X11
      - virt-manager
      - vlc
      - volumeicon
      - w3m
      - wget
      - wireshark
      - wmctrl
      - xautolock
      - xbacklight
      - xclip
      - xdotool
      - xsel
      - xset
      - zsh
    state: installed

- name: Install packages | pip
  pip:
    name:
      - busylight-for-humans
      - youtube-dl

- name: Install packages | snap
  snap:
    name:
      - dbeaver-ce
      - inkdrop
      - postman
      - slack
