---
- name: Install RVM
  shell: curl -sSL https://get.rvm.io | bash -s stable
  args:
    creates: "{{ ansible_user_dir }}/.rvm"

- name: Install Fresh
  ignore_errors: yes
  shell: curl -sL get.freshshell.com | sh
  environment:
    FRESH_LOCAL_SOURCE: lewiseason/dotfiles
  args:
    creates: "{{ ansible_user_dir }}/.dotfiles"
